# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 23:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='city',
            new_name='location',
        ),
    ]
